### ISSUE TITLE
Please Help Me!

### ISSUE THREAD

**Issue by willycode** [goonr/example_read_rails_session#1]
models/gor_user.go:14:2: cannot find package "github.com/asaskevich/govalidator" in any of:
	/usr/local/opt/go/libexec/src/github.com/asaskevich/govalidator (from $GOROOT)
	/Users/apples/.go/src/github.com/asaskevich/govalidator (from $GOPATH)
controllers/sessions_controller.go:9:3: cannot find package "github.com/bitly/go-simplejson" in any of:
	/usr/local/opt/go/libexec/src/github.com/bitly/go-simplejson (from $GOROOT)
	/Users/apples/.go/src/github.com/bitly/go-simplejson (from $GOPATH)
controllers/home_controller.go:6:2: cannot find package "github.com/gin-gonic/gin" in any of:
	/usr/local/opt/go/libexec/src/github.com/gin-gonic/gin (from $GOROOT)
	/Users/apples/.go/src/github.com/gin-gonic/gin (from $GOPATH)
controllers/sessions_controller.go:11:3: cannot find package "github.com/goonr/gorails/session" in any of:
	/usr/local/opt/go/libexec/src/github.com/goonr/gorails/session (from $GOROOT)
	/Users/apples/.go/src/github.com/goonr/gorails/session (from $GOPATH)
models/db.go:7:2: cannot find package "github.com/jmoiron/sqlx" in any of:
	/usr/local/opt/go/libexec/src/github.com/jmoiron/sqlx (from $GOROOT)
	/Users/apples/.go/src/github.com/jmoiron/sqlx (from $GOPATH)
models/db.go:6:2: cannot find package "github.com/lib/pq" in any of:
	/usr/local/opt/go/libexec/src/github.com/lib/pq (from $GOROOT)
	/Users/apples/.go/src/github.com/lib/pq (from $GOPATH)

**Comment by gingerhot** [comment]
you need install Go packages dependencies before run `go run main.go`：

```
bundle exec rails gor:deps
```
you'd better read the `Usage` of go-on-rails at first: https://github.com/goonr/go-on-rails#usage.

**Comment by willycode** [comment]
I did. But it's not work.
![screen shot 2018-02-28 at 1 48 05 pm](https://user-images.githubusercontent.com/10501241/36771958-3f59df84-1c8e-11e8-8ddf-0e81de1dd44a.png)

**Comment by gingerhot** [comment]
same problem as above. It seems that you're new to Golang? : )

you need install `github.com/bitly/go-simplejson` and `github.com/goonr/gorails/session` by:

```bash
go get github.com/bitly/go-simplejson 
go get github.com/goonr/gorails/session
```

**Comment by willycode** [comment]
Thanks. You are right. I'm new to Go before senior Rails developer.:) So I don't know that have "go get ..." the command. However, it's work. But Now I have the other problem.
![screen shot 2018-02-28 at 1 48 05 pm](https://user-images.githubusercontent.com/10501241/36781918-424da292-1cb2-11e8-998b-4a46a2a425c2.png)

**Comment by gingerhot** [comment]
it's also a Go package installation problem... It seems that your computer failed to connect to `golang.org` site. Please check your network.

**Comment by willycode** [comment]
Thank you for help. I checked my network is good. I choose the other way by download the file from github. 
`git clone https://github.com/golang/crypto.git To /Users/apples/golang/src/github.com`
It's work.
By the way, I found out one things. 
../github.com/golang/crypto  <-- before it been had the folder
So what's go in on?

**Comment by gingerhot** [comment]
It seems you'd resolved it. close now.

**Comment by willycode** [comment]
In fact it has not been completely resolved. 
session/session.go
-       "golang.org/x/crypto/pbkdf2"
+       "github.com/crypto/pbkdf2"
I found out the problem and fix it.
