### ISSUE TITLE
go run main.go pg:role does not exist

### ISSUE THREAD

**Issue by willycode** [goonr/example_read_rails_session#2]
![screen shot 2018-03-03 at 3 15 21 pm](https://user-images.githubusercontent.com/10501241/36931656-c6938c2a-1ef5-11e8-8aa2-ded91657ee7a.png)
![screen shot 2018-03-03 at 3 15 31 pm](https://user-images.githubusercontent.com/10501241/36931661-e85033f4-1ef5-11e8-8d06-8342b42af507.png)

**Comment by gingerhot** [comment]
1.  This example uses MySQL as database, not Postgres.
2.  The example means to show how to read Rails session from Go code. Not focus on how to use Postgres.

**Comment by willycode** [comment]
Thank for your response. I found https://godoc.org/github.com/lib/pq and try it in how to read Rails session from Go code. :)

**Comment by gingerhot** [comment]
In fact, go-on-rails generator support Postgres just as Rails does. I'd advised you to read the README doc in your last issue #1.

Anyway you've done it. Good job.

**Comment by willycode** [comment]
You are right. The go-on-rails will generate Postgres based Golang code. it's still no effect.
![screen shot 2018-03-05 at 2 57 08 pm](https://user-images.githubusercontent.com/10501241/36961296-9db40f64-2085-11e8-86a7-2f3c4b63561f.png)
![screen shot 2018-03-05 at 2 58 47 pm](https://user-images.githubusercontent.com/10501241/36961342-c9bbf374-2085-11e8-8f3c-34c99459c9ed.png)
![screen shot 2018-03-05 at 2 59 33 pm](https://user-images.githubusercontent.com/10501241/36961355-db779046-2085-11e8-8c08-cee1780feb77.png)
